global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # FTL GYM Application
  - job_name: 'ftl-gym-app'
    static_configs:
      - targets: ['ftl-gym-app:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Node Exporter (if needed)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Elasticsearch
  - job_name: 'elasticsearch'
    static_configs:
      - targets: ['elasticsearch:9200']
    metrics_path: '/_prometheus/metrics'

  # Redis
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  # PostgreSQL
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
